__v__ = "0.0.1"
abc = 2017-04-26T11:38:11Z
code = "0000"
msg = "处理成功"
ts = "2017-04-13 15:49:03"
ver = "1.0"
[data]
memberTel = "15001276770"
type = 1
[data.memberInfo]
address = ""
balance = "890.00"
beginDate = "2016-12-30"
birthday = "1992-09-09"
credNo = "500221199209092909"
credType = "11"
email = ""
endDate = "2999-12-31"
forever = true
id = 160389
memberName = "PJJ"
memberNo = "1500127"
memberStatus = 0
memberStatusName = "有效"
memberTypeId = 2313
memberTypeName = "白金卡"
mobile = "15001276770"
sex = 0
validScore = 999
