

is_intercept_error = true

[error_page]
404 = "/404.html"
500 = "/500.html"

[server]
name = "sugar 2.0"
port = "8080"

[monitor]
enabled = true
port = 2013
host = "qmon-beta.corp.qunar.com"
prefix = "s.sp.fore.market"

[log]
enabled = true
level = 1 # 1=trace 2=debug 3=info 4=warn 5=error 6=fatal
log_name = "app_yyyy-MM-dd.log" #yyyy=年 MM=月 dd=日 hh=时 mm=分 ss=秒
root = "/logs/app"

[ral]

[ral.ral_config_name_1]
type = "http"
method = "GET"
timeout = 10
retry = 2

[ral.ral_config_name_2]
type = "http"
method = "GET"
timeout = 10
retry = 2

[view]
root = "/view"
engine = "ejs"

[static]
root = "/static"

[database]
